/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Mon May 20 17:27:22 2019. */

#include "common.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ledgervault_VersionnedObject_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, ledgervault_VersionnedObject, magic, magic, 0),
    PB_FIELD(  2, FIXED_LENGTH_BYTES, OPTIONAL, STATIC  , OTHER, ledgervault_VersionnedObject, id, magic, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, STATIC  , OTHER, ledgervault_VersionnedObject, antiReplayReference, id, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, ledgervault_VersionnedObject, antiReplayValue, antiReplayReference, 0),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_LightVersionnedObjectRef_fields[4] = {
    PB_FIELD(  1, FIXED_LENGTH_BYTES, OPTIONAL, STATIC  , FIRST, ledgervault_LightVersionnedObjectRef, id, id, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, ledgervault_LightVersionnedObjectRef, version, id, 0),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, ledgervault_LightVersionnedObjectRef, seen, version, 0),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_LightVersionnedObject_fields[4] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, ledgervault_LightVersionnedObject, magic, magic, 0),
    PB_FIELD(  2, FIXED_LENGTH_BYTES, OPTIONAL, STATIC  , OTHER, ledgervault_LightVersionnedObject, id, magic, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, ledgervault_LightVersionnedObject, version, id, 0),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_Certificate_fields[5] = {
    PB_FIELD(  1, FIXED_LENGTH_BYTES, SINGULAR, STATIC  , FIRST, ledgervault_Certificate, codeHash, codeHash, 0),
    PB_FIELD(  2, FIXED_LENGTH_BYTES, SINGULAR, STATIC  , OTHER, ledgervault_Certificate, attestationPub, codeHash, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, STATIC  , OTHER, ledgervault_Certificate, certificate, attestationPub, 0),
    PB_FIELD(  4, BYTES   , SINGULAR, STATIC  , OTHER, ledgervault_Certificate, signature, certificate, 0),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_Bip32Path_fields[2] = {
    PB_FIELD(  1, UINT32  , REPEATED, STATIC  , FIRST, ledgervault_Bip32Path, pathElement, pathElement, 0),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_TrustedScript_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, POINTER , FIRST, ledgervault_TrustedScript, name, name, 0),
    PB_FIELD(  2, FIXED_LENGTH_BYTES, SINGULAR, POINTER , OTHER, ledgervault_TrustedScript, codeHash, name, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, ledgervault_TrustedScript, version, codeHash, 0),
    PB_FIELD(  4, MESSAGE , SINGULAR, POINTER , OTHER, ledgervault_TrustedScript, certificate, version, &ledgervault_Certificate_fields),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
