/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Mon May 20 17:27:22 2019. */

#include "error.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ledgervault_ExceptionResponse_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, ledgervault_ExceptionResponse, errorCode, errorCode, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, ledgervault_ExceptionResponse, exception, errorCode, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for ledgervault_ExceptionResponse.exception is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
