/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Mon May 20 17:27:22 2019. */

#include "init.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ledgervault_WrapFragment_fields[4] = {
    PB_FIELD(  1, FIXED_LENGTH_BYTES, SINGULAR, STATIC  , FIRST, ledgervault_WrapFragment, ephemeralPublicKey, ephemeralPublicKey, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, ledgervault_WrapFragment, certificate, ephemeralPublicKey, &ledgervault_Certificate_fields),
    PB_FIELD(  3, BYTES   , SINGULAR, STATIC  , OTHER, ledgervault_WrapFragment, wrapBlob, certificate, 0),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_InitiateWrapProvisioning_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, ledgervault_InitiateWrapProvisioning, shardNumbers, shardNumbers, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, ledgervault_InitiateWrapProvisioning, index, shardNumbers, 0),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_InitiateWrapProvisioningResponse_fields[3] = {
    PB_FIELD(  1, FIXED_LENGTH_BYTES, SINGULAR, STATIC  , FIRST, ledgervault_InitiateWrapProvisioningResponse, ephemeralPublicKey, ephemeralPublicKey, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, ledgervault_InitiateWrapProvisioningResponse, certificate, ephemeralPublicKey, &ledgervault_Certificate_fields),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_SubmitWrapFragments_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, POINTER , FIRST, ledgervault_SubmitWrapFragments, fragments, fragments, &ledgervault_WrapFragment_fields),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_SubmitWrapFragmentsResponse_fields[2] = {
    PB_FIELD(  1, BYTES   , SINGULAR, STATIC  , FIRST, ledgervault_SubmitWrapFragmentsResponse, wrapChecksum, wrapChecksum, 0),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_InitRequest_fields[3] = {
    PB_ANONYMOUS_ONEOF_FIELD(one,   1, MESSAGE , ONEOF, STATIC  , FIRST, ledgervault_InitRequest, InitiateWrapProvisioning, InitiateWrapProvisioning, &ledgervault_InitiateWrapProvisioning_fields),
    PB_ANONYMOUS_ONEOF_FIELD(one,   2, MESSAGE , ONEOF, STATIC  , UNION, ledgervault_InitRequest, SubmitWrapFragments, SubmitWrapFragments, &ledgervault_SubmitWrapFragments_fields),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_InitResponse_fields[4] = {
    PB_ANONYMOUS_ONEOF_FIELD(one,   1, MESSAGE , ONEOF, STATIC  , FIRST, ledgervault_InitResponse, InitiateWrapProvisioningResponse, InitiateWrapProvisioningResponse, &ledgervault_InitiateWrapProvisioningResponse_fields),
    PB_ANONYMOUS_ONEOF_FIELD(one,   2, MESSAGE , ONEOF, STATIC  , UNION, ledgervault_InitResponse, SubmitWrapFragmentsResponse, SubmitWrapFragmentsResponse, &ledgervault_SubmitWrapFragmentsResponse_fields),
    PB_ANONYMOUS_ONEOF_FIELD(one, 999, MESSAGE , ONEOF, STATIC  , UNION, ledgervault_InitResponse, ExceptionResponse, ExceptionResponse, &ledgervault_ExceptionResponse_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ledgervault_WrapFragment, certificate) < 65536 && pb_membersize(ledgervault_InitiateWrapProvisioningResponse, certificate) < 65536 && pb_membersize(ledgervault_InitRequest, InitiateWrapProvisioning) < 65536 && pb_membersize(ledgervault_InitRequest, SubmitWrapFragments) < 65536 && pb_membersize(ledgervault_InitResponse, InitiateWrapProvisioningResponse) < 65536 && pb_membersize(ledgervault_InitResponse, SubmitWrapFragmentsResponse) < 65536 && pb_membersize(ledgervault_InitResponse, ExceptionResponse) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ledgervault_WrapFragment_ledgervault_InitiateWrapProvisioning_ledgervault_InitiateWrapProvisioningResponse_ledgervault_SubmitWrapFragments_ledgervault_SubmitWrapFragmentsResponse_ledgervault_InitRequest_ledgervault_InitResponse)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for ledgervault_InitResponse.ExceptionResponse is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
