/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Tue May 21 16:09:25 2019. */

#include "multiSigARPsd.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ledgervault_psd_MultiSigAR_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, POINTER , FIRST, ledgervault_psd_MultiSigAR, groups, groups, &ledgervault_psd_MultiSigOperatorGroup_fields),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_psd_MultiSigOperatorGroup_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, ledgervault_psd_MultiSigOperatorGroup, M, M, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, ledgervault_psd_MultiSigOperatorGroup, MNew, M, 0),
    PB_ANONYMOUS_ONEOF_FIELD(one,   3, MESSAGE , ONEOF, STATIC  , OTHER, ledgervault_psd_MultiSigOperatorGroup, internalGroup, MNew, &ledgervault_psd_MultiSigOperatorGroup_InternalOperatorGroup_fields),
    PB_ANONYMOUS_ONEOF_FIELD(one,   4, MESSAGE , ONEOF, STATIC  , UNION, ledgervault_psd_MultiSigOperatorGroup, externalGroup, MNew, &ledgervault_psd_MultiSigOperatorGroup_ExternalOperatorGroup_fields),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_psd_MultiSigOperatorGroup_ExternalOperatorGroup_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, POINTER , FIRST, ledgervault_psd_MultiSigOperatorGroup_ExternalOperatorGroup, name, name, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, ledgervault_psd_MultiSigOperatorGroup_ExternalOperatorGroup, N, name, 0),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_psd_MultiSigOperatorGroup_InternalOperatorGroup_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, POINTER , FIRST, ledgervault_psd_MultiSigOperatorGroup_InternalOperatorGroup, users, users, &ledgervault_psd_User_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ledgervault_psd_MultiSigOperatorGroup, internalGroup) < 65536 && pb_membersize(ledgervault_psd_MultiSigOperatorGroup, externalGroup) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ledgervault_psd_MultiSigAR_ledgervault_psd_MultiSigOperatorGroup_ledgervault_psd_MultiSigOperatorGroup_ExternalOperatorGroup_ledgervault_psd_MultiSigOperatorGroup_InternalOperatorGroup)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ledgervault_psd_MultiSigOperatorGroup, internalGroup) < 256 && pb_membersize(ledgervault_psd_MultiSigOperatorGroup, externalGroup) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_ledgervault_psd_MultiSigAR_ledgervault_psd_MultiSigOperatorGroup_ledgervault_psd_MultiSigOperatorGroup_ExternalOperatorGroup_ledgervault_psd_MultiSigOperatorGroup_InternalOperatorGroup)
#endif


/* @@protoc_insertion_point(eof) */
