/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Tue May 21 17:16:27 2019. */

#include "psd.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ledgervault_psd_User_fields[7] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, ledgervault_psd_User, type, type, 0),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, ledgervault_psd_User, role, type, 0),
    PB_FIELD(  3, STRING  , SINGULAR, POINTER , OTHER, ledgervault_psd_User, name, role, 0),
    PB_FIELD(  4, STRING  , SINGULAR, POINTER , OTHER, ledgervault_psd_User, nameNew, name, 0),
    PB_FIELD(  5, FIXED_LENGTH_BYTES, SINGULAR, STATIC  , OTHER, ledgervault_psd_User, confidentialityKey, nameNew, 0),
    PB_FIELD(  6, UENUM   , SINGULAR, STATIC  , OTHER, ledgervault_psd_User, status, confidentialityKey, 0),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_psd_AdminGroup_fields[8] = {
    PB_FIELD(  1, STRING  , SINGULAR, POINTER , FIRST, ledgervault_psd_AdminGroup, name, name, 0),
    PB_FIELD(  2, STRING  , SINGULAR, POINTER , OTHER, ledgervault_psd_AdminGroup, nameNew, name, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, ledgervault_psd_AdminGroup, policyM, nameNew, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, ledgervault_psd_AdminGroup, policyMNew, policyM, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, ledgervault_psd_AdminGroup, policyM_ReadOnlyWallet, policyMNew, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, ledgervault_psd_AdminGroup, policyM_ReadOnlyWalletNew, policyM_ReadOnlyWallet, 0),
    PB_FIELD(  7, MESSAGE , REPEATED, POINTER , OTHER, ledgervault_psd_AdminGroup, users, policyM_ReadOnlyWalletNew, &ledgervault_psd_User_fields),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_psd_OperatorGroup_fields[6] = {
    PB_FIELD(  1, STRING  , SINGULAR, POINTER , FIRST, ledgervault_psd_OperatorGroup, name, name, 0),
    PB_FIELD(  2, STRING  , SINGULAR, POINTER , OTHER, ledgervault_psd_OperatorGroup, nameNew, name, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, ledgervault_psd_OperatorGroup, revoked, nameNew, 0),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, ledgervault_psd_OperatorGroup, revokedNew, revoked, 0),
    PB_FIELD(  7, MESSAGE , REPEATED, POINTER , OTHER, ledgervault_psd_OperatorGroup, users, revokedNew, &ledgervault_psd_User_fields),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_psd_Partition_fields[7] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, ledgervault_psd_Partition, bootstrapEnabled, bootstrapEnabled, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, ledgervault_psd_Partition, bootstrapEnabledNew, bootstrapEnabled, 0),
    PB_FIELD(  3, STRING  , SINGULAR, POINTER , OTHER, ledgervault_psd_Partition, workspaceName, bootstrapEnabledNew, 0),
    PB_FIELD(  4, STRING  , SINGULAR, POINTER , OTHER, ledgervault_psd_Partition, workspaceNameNew, workspaceName, 0),
    PB_FIELD(  7, MESSAGE , REPEATED, POINTER , OTHER, ledgervault_psd_Partition, adminGroups, workspaceNameNew, &ledgervault_psd_AdminGroup_fields),
    PB_FIELD(  8, MESSAGE , REPEATED, POINTER , OTHER, ledgervault_psd_Partition, sharedOwners, adminGroups, &ledgervault_psd_User_fields),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_psd_AccountRule_fields[5] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, ledgervault_psd_AccountRule, type, type, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, POINTER , OTHER, ledgervault_psd_AccountRule, payload, type, 0),
    PB_FIELD(  3, UENUM   , SINGULAR, STATIC  , OTHER, ledgervault_psd_AccountRule, status, payload, 0),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, ledgervault_psd_AccountRule, updated, status, 0),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_psd_AccountRuleSet_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, POINTER , FIRST, ledgervault_psd_AccountRuleSet, name, name, 0),
    PB_FIELD(  2, STRING  , SINGULAR, POINTER , OTHER, ledgervault_psd_AccountRuleSet, nameNew, name, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, POINTER , OTHER, ledgervault_psd_AccountRuleSet, accountRules, nameNew, &ledgervault_psd_AccountRule_fields),
    PB_FIELD(  4, UENUM   , SINGULAR, STATIC  , OTHER, ledgervault_psd_AccountRuleSet, status, accountRules, 0),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_psd_Account_fields[4] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, ledgervault_psd_Account, wallet, wallet, &ledgervault_psd_Account_Wallet_fields),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, ledgervault_psd_Account, account, wallet, &ledgervault_psd_Account_Account_fields),
    PB_FIELD( 11, MESSAGE , REPEATED, POINTER , OTHER, ledgervault_psd_Account, accountRuleSets, account, &ledgervault_psd_AccountRuleSet_fields),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_psd_Account_Wallet_fields[6] = {
    PB_FIELD(  1, STRING  , SINGULAR, POINTER , FIRST, ledgervault_psd_Account_Wallet, name, name, 0),
    PB_FIELD(  2, STRING  , SINGULAR, POINTER , OTHER, ledgervault_psd_Account_Wallet, nameNew, name, 0),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, ledgervault_psd_Account_Wallet, bip32Path, nameNew, &ledgervault_Bip32Path_fields),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, ledgervault_psd_Account_Wallet, archived, bip32Path, 0),
    PB_FIELD(  5, BOOL    , SINGULAR, STATIC  , OTHER, ledgervault_psd_Account_Wallet, archivedNew, archived, 0),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_psd_Account_Account_fields[6] = {
    PB_FIELD(  6, STRING  , SINGULAR, POINTER , FIRST, ledgervault_psd_Account_Account, name, name, 0),
    PB_FIELD(  7, STRING  , SINGULAR, POINTER , OTHER, ledgervault_psd_Account_Account, nameNew, name, 0),
    PB_FIELD(  8, UENUM   , SINGULAR, STATIC  , OTHER, ledgervault_psd_Account_Account, currencyScriptType, nameNew, 0),
    PB_FIELD(  9, BOOL    , SINGULAR, STATIC  , OTHER, ledgervault_psd_Account_Account, archived, currencyScriptType, 0),
    PB_FIELD( 10, BOOL    , SINGULAR, STATIC  , OTHER, ledgervault_psd_Account_Account, archivedNew, archived, 0),
    PB_LAST_FIELD
};

const pb_field_t ledgervault_psd_PsdRequest_fields[6] = {
    PB_FIELD(  1, FIXED_LENGTH_BYTES, SINGULAR, STATIC  , FIRST, ledgervault_psd_PsdRequest, challenge, challenge, 0),
    PB_ANONYMOUS_ONEOF_FIELD(one,   2, MESSAGE , ONEOF, POINTER , OTHER, ledgervault_psd_PsdRequest, Partition, challenge, &ledgervault_psd_Partition_fields),
    PB_ANONYMOUS_ONEOF_FIELD(one,   3, MESSAGE , ONEOF, POINTER , UNION, ledgervault_psd_PsdRequest, OperatorGroup, challenge, &ledgervault_psd_OperatorGroup_fields),
    PB_ANONYMOUS_ONEOF_FIELD(one,   4, MESSAGE , ONEOF, POINTER , UNION, ledgervault_psd_PsdRequest, User, challenge, &ledgervault_psd_User_fields),
    PB_ANONYMOUS_ONEOF_FIELD(one,   5, MESSAGE , ONEOF, POINTER , UNION, ledgervault_psd_PsdRequest, Account, challenge, &ledgervault_psd_Account_fields),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ledgervault_psd_Account, wallet) < 65536 && pb_membersize(ledgervault_psd_Account, account) < 65536 && pb_membersize(ledgervault_psd_Account_Wallet, bip32Path) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ledgervault_psd_User_ledgervault_psd_AdminGroup_ledgervault_psd_OperatorGroup_ledgervault_psd_Partition_ledgervault_psd_AccountRule_ledgervault_psd_AccountRuleSet_ledgervault_psd_Account_ledgervault_psd_Account_Wallet_ledgervault_psd_Account_Account_ledgervault_psd_PsdRequest)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ledgervault_psd_Account, wallet) < 256 && pb_membersize(ledgervault_psd_Account, account) < 256 && pb_membersize(ledgervault_psd_Account_Wallet, bip32Path) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_ledgervault_psd_User_ledgervault_psd_AdminGroup_ledgervault_psd_OperatorGroup_ledgervault_psd_Partition_ledgervault_psd_AccountRule_ledgervault_psd_AccountRuleSet_ledgervault_psd_Account_ledgervault_psd_Account_Wallet_ledgervault_psd_Account_Account_ledgervault_psd_PsdRequest)
#endif


/* @@protoc_insertion_point(eof) */
