/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Tue May 21 16:09:25 2019. */

#include "vault.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ledgervault_OperatorUpdate_fields[3] = {
    PB_FIELD(  1, BYTES   , SINGULAR, POINTER , FIRST, ledgervault_OperatorUpdate, wOperator, wOperator, 0),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, ledgervault_OperatorUpdate, status, wOperator, 0),
    PB_LAST_FIELD
};







/* @@protoc_insertion_point(eof) */
